# Generated by Django 3.2.7 on 2021-10-05 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(default='', max_length=254)),
                ('username', models.CharField(max_length=254, unique=True)),
                ('last_name', models.CharField(default='', max_length=254)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('account_updated', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
