# inside .github/workflows/your-action.yml
name: Add File to Bucket
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Check
      run: |
        echo $(ls)
    - name: Release to S3
      run: bash scripts/pipeline/release.sh ${{ secrets.AWS_Bucket_Name }} "webapp.zip" ${{ secrets.AWS_Access_Key }} ${{ secrets.AWS_Access_Secret }} "webapp.zip"
